CREATE TABLE updates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL,
    up_votes INTEGER DEFAULT 0,
    down_votes INTEGER DEFAULT 0,
    verdict TEXT DEFAULT 'WAIT',
    last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);